### PR TITLE
ARMv6: fix setting the CONTROL register

### LINKED ISSUE #4245: ARMv6m: Register clobbering in Generic ISR causes exception exit to return to process rather than Kernel
I'm opening this issue following the discussion in #4242.

In the v6m `generic_isr` exceptions handled when running a process seems to return to that process rather than the kernel. On [this line](https://github.com/tock/tock/blob/a1966b8ddaa1ce819b80f2f7bea466eb76e5b46c/arch/cortex-m0/src/lib.rs#L116), we load the special MSP return value into `r0`, but unfortunately we clobber it on the [next line](https://github.com/tock/tock/blob/a1966b8ddaa1ce819b80f2f7bea466eb76e5b46c/arch/cortex-m0/src/lib.rs#L119). When we return from the ISR [here](https://github.com/tock/tock/blob/a1966b8ddaa1ce819b80f2f7bea466eb76e5b46c/arch/cortex-m0/src/lib.rs#L155C8-L155C10) I believe the value of `lr` is `0xFFFFFFFD` which will cause a return to the process rather than the kernel. 

I think it suffices to move `ldr r0, 200f` to line `155` before we [return from the exception](https://github.com/tock/tock/blob/a1966b8ddaa1ce819b80f2f7bea466eb76e5b46c/arch/cortex-m0/src/lib.rs#L155). This is redundant but follows a similar pattern to what's done in `v7m` where we load the MSP return value `0xFFFFFFF9` into the link register unconditionally.

### LINKED ISSUE #4246: ARMv6m: Thread mode not set to privileged execution in certain ISRs
I'm opening this issue following the discussion in #4242.

I believe that the following ISRs need to set the special `CONTROL` register to `0` before exception return, similar to [the `systick_handler`](https://github.com/tock/tock/blob/a1966b8ddaa1ce819b80f2f7bea466eb76e5b46c/arch/cortex-m0/src/lib.rs#L189) on [line 193](https://github.com/tock/tock/blob/a1966b8ddaa1ce819b80f2f7bea466eb76e5b46c/arch/cortex-m0/src/lib.rs#L193)

- [Generic ISR](https://github.com/tock/tock/blob/a1966b8ddaa1ce819b80f2f7bea466eb76e5b46c/arch/cortex-m0/src/lib.rs#L89)
     - I think that this is canceled out by #4245., since we return to the process rather than the kernel when coming from a process. 
- [SVC Handler](https://github.com/tock/tock/blob/a1966b8ddaa1ce819b80f2f7bea466eb76e5b46c/arch/cortex-m0/src/lib.rs#L226)      
     - My hunch here is that we should be setting thread mode to privileged execution in the case we are coming from a process and need to return to the kernel to handle a syscall. I think setting the `CONTROL` register to `0` [here](https://github.com/tock/tock/blob/a1966b8ddaa1ce819b80f2f7bea466eb76e5b46c/arch/cortex-m0/src/lib.rs#L233) should do the trick. Similar to how the `v7m svc handler`  does [here](https://github.com/tock/tock/blob/a1966b8ddaa1ce819b80f2f7bea466eb76e5b46c/arch/cortex-v7m/src/lib.rs#L121).
    - It might also be a good idea to ensure that we set thread mode to unprivileged execution when we go from kernel to process. It seems like the `v7m svc handler` does this [here](https://github.com/tock/tock/blob/a1966b8ddaa1ce819b80f2f7bea466eb76e5b46c/arch/cortex-v7m/src/lib.rs#L90).

### PR DESCRIPTION
**Pull request by alexandruradovici**
### Pull Request Overview

This pull request fixes a fault in `generic_isr` and `svc_handler` by setting the `CONTROL` register accordingly. Without this fix, after an interrupt, applications continue to work in privileged mode.

This fixes #4245 and fixes #4246.

### Testing Strategy

This pull request was tested using a Raspberry Pi Pico by @JADarius.

### TODO or Help Wanted

Feedback from @ppannuto and others that are more experienced in ARM architecture.

### Documentation Updated

- [x] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [x] Ran `make prepush`.

### CODE REVIEW

**Review by bradjc — APPROVED** [review]

File: arch/cortex-m0/src/lib.rs [hunk 1]
```diff
@@ -92,6 +92,13 @@ core::arch::global_asm!(
     cmp lr, r0
     bne 100f
 
+    /* We need to make sure the kernel cotinues the execution after this ISR */
+    movs r0, #0
+    msr CONTROL, r0
+    /* CONTROL writes must be followed by ISB */
+    /* http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dai0321a/BIHFJCAC.html */
```
Comment (brghena) [inline arch/cortex-m0/src/lib.rs:99]: This link doesn't work for me. When I try to follow it, it just dumps me in the main ARM documentation page.

Comment (brghena) [reply arch/cortex-m0/src/lib.rs:99]: Same problem for the other two copies of this link below.

File: arch/cortex-m0/src/lib.rs [hunk 2]
```diff
@@ -114,6 +121,7 @@ core::arch::global_asm!(
     pop {{r4-r7}}
 
     ldr r0, 200f // MEXC_RETURN_MSP
+    mov lr, r0
```
Comment (brghena) [inline arch/cortex-m0/src/lib.rs:124]: Can you comment on this additional change? The line before this was definitely pointless previously. But it's been like that for years apparently without an issue?

**Review by brghena — CHANGES_REQUESTED** [review]

File: arch/cortex-m0/src/lib.rs (hunk 2 above)
Comment (alevy) [reply arch/cortex-m0/src/lib.rs:124]: I don't think it's necessarily been without issue, we just haven't had an armv6m platform since the nrf51 until the rp2040

File: arch/cortex-m0/src/lib.rs (hunk 1 above)
Comment (lschuermann) [reply arch/cortex-m0/src/lib.rs:99]: @alexandruradovici Can you fix this? I'd like to get this PR in before tagging a release candidate.

**Review by lschuermann — APPROVED** [review]
This makes sense to me.

I guess it's kind of weird that we're doing an `msr CONTROL, #1` which set unprivileged mode and MSP stack, and then immediately afterwards jumping to `0xFFFFFFFD` which returns to the PSP stack (so the intermediate transition to the MSP stack seems unnecessary), but I also don't see anything _wrong_ with that, and maybe that's just how ARM works? :shrug:

File: arch/cortex-m0/src/lib.rs (hunk 1 above)
Comment (lschuermann) [reply arch/cortex-m0/src/lib.rs:99]: This seems to be an alternative
```suggestion
    /* https://developer.arm.com/documentation/dui0662/b/The-Cortex-M0--Processor/Programmers-model/Core-registers */
```

Comment (alevy) [reply arch/cortex-m0/src/lib.rs:99]: @alexandruradovici can you hit commit on this change so we can merge this PR?

**Review by brghena — DISMISSED** [review]
I guess I have to switch to "approve" to remove it.

File: arch/cortex-m0/src/lib.rs [hunk 3]
```diff
@@ -227,10 +235,20 @@ svc_handler:
   ldr r0, 200f // EXC_RETURN_MSP
   cmp lr, r0
   bne 100f
+  movs r0, #1
+  msr CONTROL, r0
+  /* CONTROL writes must be followed by ISB */
+  /* http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dai0321a/BIHFJCAC.html */
```
Comment (lschuermann) [inline arch/cortex-m0/src/lib.rs:241]:
```suggestion
    /* https://developer.arm.com/documentation/dui0662/b/The-Cortex-M0--Processor/Programmers-model/Core-registers */
```

File: arch/cortex-m0/src/lib.rs [hunk 4]
```diff
@@ -227,10 +235,20 @@ svc_handler:
...
+  isb
   ldr r1, 300f // EXC_RETURN_PSP
   bx r1
 
 100: // to_kernel
+  movs r0, #0
+  msr CONTROL, r0
+  /* CONTROL writes must be followed by ISB */
+  /* http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dai0321a/BIHFJCAC.html */
```
Comment (lschuermann) [inline arch/cortex-m0/src/lib.rs:250]:
```suggestion
    /* https://developer.arm.com/documentation/dui0662/b/The-Cortex-M0--Processor/Programmers-model/Core-registers */
```

**Review by lschuermann — CHANGES_REQUESTED** [review]
Proposed changes for the other occurrences too.

**Review by alevy — APPROVED** [review]

**Comment by vrindisbacher** [comment]
@lschuermann, r.e. "I guess it's kind of weird that we're doing an msr CONTROL, #1 which set unprivileged mode and MSP stack...".

This is strange for sure, as it looks like `msr` updates the `spsel` bit of the `CONTROL` register. Luckily, writes to the CONTROL's `spsel` bit (the bit that controls the stack used) are **ignored in handler mode**. So in effect, this will just write to the `npriv` bit. Here is the ARM pseudo code for the instruction (see page B5-678 of the manual): 

```
if CurrentModeIsPrivileged() then
 CONTROL.nPRIV = R[n]<0>;
 if CurrentMode == Mode_Thread then
 CONTROL.SPSEL = R[n]<1>;
```

**Comment by lschuermann** [comment]
> This is strange for sure, as it looks like `msr` updates the `spsel` bit of the `CONTROL` register. Luckily, writes to the CONTROL's `spsel` bit (the bit that controls the stack used) are **ignored in handler mode**. So in effect, this will just write to the `npriv` bit. Here is the ARM pseudo code for the instruction (see page B5-678 of the manual):

Wow, that behavior is so much worse than I expected it to be. Thanks for clarifying!

**Review by lschuermann — APPROVED** [review]
Delegating merging this to @alevy, as discussed on the core WG call today.

**Review by alevy — APPROVED** [review]
