### PR TITLE
RISCV: Allow extended values of interrupt IDs in MCAUSE

### LINKED ISSUE #4352: [RISCV] "Non-standard" mcause bits are lost in conversion
In this code:

https://github.com/tock/tock/blob/22ab469dfe3aeaac01e3947aedabacf0a697d312/arch/riscv/src/csr/mcause.rs#L5-L19

the `reason` field is 4-bit wide, and the comment is explaining why. But there is a problem if an implementation actually needs the higher values. The issue stems from the `Interrupt::from_reason()` implementation:

https://github.com/tock/tock/blob/22ab469dfe3aeaac01e3947aedabacf0a697d312/arch/riscv/src/csr/mcause.rs#L79-L95

Since it is considering only 4 bits of `reason`, any value with `mcause.EXCCODE` higher than `15` will be misinterpreted. Here is the panic I am seeing on my run:
```
unexpected user-mode interrupt
        Kernel version unknown

---| RISC-V Machine State |---
Last cause (mcause): User software interrupt (interrupt=1, exception code=0x00000010)
Last value (mtval):  0x00000000

System register dump:
 mepc:    0x00803568    mstatus:     0x00001880
 mcycle:  0x00C11870    minstret:    0x000F0AC2
 mtvec:   0x00800100
 mstatus: 0x00001880
  uie:    false  upie:   false
  sie:    false  spie:   false
  mie:    false  mpie:   true
  spp:    false
 mie:   0x00010888   mip:   0x00010800
  usoft:  false               false
  ssoft:  false               false
  msoft:  true                false
  utimer: false               false
  stimer: false               false
  mtimer: true                false
  uext:   false               false
  sext:   false               false
  mext:   true                true
```

Specifically the line 
> Last cause (mcause): User software interrupt (interrupt=1, exception code=0x00000010)

As we can see, the actual "reason" is interrupt number `0x10` (which in my case is a LocalInterrupt0), but it is misinterpreted as User software interrupt (interrupt number `0`).

Since this is happening on the `arch::riscv` level, there is no way to fix it on the board/chip level. 
I think the bitness limit of `reason` should be removed. The unknown values will still be mapped to `Interrupt::Unknown` without breaking anything, but will also give the downstream code to handle it appropriately (but ideally, of course, it should be "extendable" somehow for the specific implementation).

### PR DESCRIPTION
**Pull request by ZhekaS**
Fixes #4352

### Pull Request Overview

The `mcause.EXCCODE` might contain values > 15 for specific implementations. These should be supported. The previous implementation only considered 4 bits of the code, misinterpreting any value >15.

This PR removes this limitation and allows passing the exact `macause.EXCCODE` value to the interrupt handler wrapped in `Interrupt::Unknown(_)` variant instead of just passing field-less `Interrupt::Unknown`.

### Testing Strategy

Tested on local simulated RISCV environment
Tested build only on affected RiscV board crates

### Help Wanted

Test on physical boards affected

### CODE REVIEW

**Review by brghena — APPROVED** [review]
Makes sense to me

File: arch/rv32i/src/lib.rs [hunk 1]
```diff
@@ -454,7 +454,7 @@ pub unsafe fn print_mcause(mcval: csr::mcause::Trap, writer: &mut dyn Write) {
             csr::mcause::Interrupt::MachineExternal => {
                 let _ = writer.write_fmt(format_args!("Machine external interrupt"));
             }
-            csr::mcause::Interrupt::Unknown => {
+            csr::mcause::Interrupt::Unknown(_) => {
                 let _ = writer.write_fmt(format_args!("Reserved/Unknown"));
```
Comment (bradjc) [inline arch/rv32i/src/lib.rs:458]: Why not print the ID?

**Review by bradjc — APPROVED** [review]

File: arch/rv32i/src/lib.rs (hunk 1 above)
Comment (ZhekaS) [reply arch/rv32i/src/lib.rs:458]: It is used in panic only as for now, and the whole mcause value is printed anyway (as I show in the linked issue). So I thought it might not be necessary

**Review by alistair23 — APPROVED** [review]
