### PR TITLE
Isolated NonVolatile Storage Capsule Bug Fixes

### LINKED ISSUE #4453: Isolated NonVolatile Storage Capsule - Flash Write Silent Failure
The existing Isolated NonVolatile Storage Capsule must initiate synchronous work to determine the app regions/sizing/availability. As such, Isolated NV syscalls enqueue the commands and return a `CommandReturn` to userspace with minimal checks.

To perform NV writes, we utilize a kernel buffer and copy to the kernel buffer from an allowed userspace buffer. We must ensure that the kernel buffer is large enough to hold the userspace allowed buffer. 

Currently, the isolated nv capsule performs the following calculation to determine how many bytes to write:

```Rust
// Check that the internal buffer and
// the buffer that was allowed are long
// enough.
let write_len = cmp::min(allow_buf_len, kernel_buffer.len());
```

If the kernel buffer is smaller than the buffer the application allows and is attempting to write, the current implementation will:
- write bytes `0 => kernel_buffer.len()` 
- will not write bytes `kernel_buffer.len() => allowed_buffer.len()`
- the capsule returns an upcall with a `Success` (silent failure).

---
*Note: This bug does not apply to the check for reads in the isolated nv capsule. In this case, taking the minimum is correct and will not result in a silent failure.

### LINKED ISSUE #4454: Isolated NonVolatile Storage Capsule - Flash Access Location Miscalculation
## Overview

The isolated NV storage capsule is intended to specify a region upon construction which it can own and exclusively perform reads/writes within. As currently implemented, the capsule miscomputes the address in flash where it performs reads writes (mapping from an app's perception of the isolated flash to the physical address of flash).

### Bug 

```Rust
// Calculate where we want to actually read from in the
// physical storage. Note that the given offset for this
// command is with respect to the app's region address
// space. This means that userspace accesses start at 0
// which is the start of the app's region.
let physical_address = app_region.offset + command_offset + self.userspace_start_address;
```

The `app_region.offset` and `self.userspace_start_address` represent the same value per the documentation comments below:
```Rust
/// Absolute address to describe where an app's nonvolatile region starts.
/// Note that this is the address FOLLOWING the region's header.
offset: usize,
```

```Rust
/// The first byte that is accessible from userspace.
 userspace_start_address: usize,
```

Calculating the physical address using both `app_region.offset` and `self.userspace_start_address` is incorrect as the `app_region.offset` is the absolute address. 

### Resulting Behavior

This bug results in the isolated nv storage capsule writing flash outside the allocated region. When tested with a sufficiently large (e.g. OpenThread) app, this resulted in the isolated nv storage capsule overwriting the app's `text` region.

### PR DESCRIPTION
**Pull request by tyler-potyondy**
### Pull Request Overview

This pull request fixes #4453 and #4454. 

Respectively:
- Commit (afbcb89d5868f45b4b777ce330cec76e6bae444a) fixes #4453 
- Commit (08855c8a732fbb34c32a4a649a2cccc1dba3401e) fixes #4454 

This PR also adds some naming fixes for the `AppRegion` member `offset` as this name is somewhat a misnomer given this member representing an absolute address.

### Testing Strategy

This pull request was tested using the `libtock-c/examples/tests/isolated_nonvolatile_storage/invs_read_write` test and the OpenThread apps (which use the isolated nv capsule).

### TODO or Help Wanted

I would appreciate a sanity check from @bradjc and @atar13 on the `offset` member in fact being an absolute address as mentioned in the doc comment. Looking at all usages, this appears to be true.

### Documentation Updated

- [x] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [x] Ran `make prepush`.

### CODE REVIEW

**Comment by bradjc** [comment]
Yeah wow, #4454 is a bad mistake. Thanks for fixing this.

I'm not sure that #4453 is actually a problem; the truncated write happens and the length of the actual write is reported to userspace. If userspace doesn't think that is enough it can do another write. It would be better for the capsule to loop to do all of the writing, but I think truncating is better than having userspace have to keep guessing how long the kernel buffer is to do a write.

**Comment by tyler-potyondy** [comment]
> I'm not sure that https://github.com/tock/tock/issues/4453 is actually a problem; the truncated write happens and the length of the actual write is reported to userspace. If userspace doesn't think that is enough it can do another write. It would be better for the capsule to loop to do all of the writing, but I think truncating is better than having userspace have to keep guessing how long the kernel buffer is to do a write.

This is a fair point and seems reasonable as an interface. Looking further (unless I'm missing something) this doesn't seem to be the case from the interface we expose in `libtock-c` (although this is in built into the capsule). It seems a better path forward is updating the libtock-c interface.

**Comment by tyler-potyondy** [comment]
I've removed the commit regarding #4453.

File: capsules/extra/src/isolated_nonvolatile_storage_driver.rs [hunk 1]
```diff
@@ -161,7 +161,7 @@ pub struct AppRegion {
     version: HeaderVersion,
     /// Absolute address to describe where an app's nonvolatile region starts.
     /// Note that this is the address FOLLOWING the region's header.
-    offset: usize,
+    global_address: usize,
```
Comment (ppannuto) [inline capsules/extra/src/isolated_nonvolatile_storage_driver.rs]:
```suggestion
    absolute_address: usize,
```

I wasn't quite sure on first read what a "global" address was. I was going to suggest changing this to `physical_address`, but that's used differently later (to hold result of `absolute_address + offset`). I think the comment on this variable found a good word, and we should be consistent.

Comment (bradjc) [reply capsules/extra/src/isolated_nonvolatile_storage_driver.rs]: What about just `address`? I agree that offset is totally wrong, but if this wasn't fixing an issue we would probably just call this "address".

Comment (tyler-potyondy) [reply capsules/extra/src/isolated_nonvolatile_storage_driver.rs]: Personally, I like the "physical" qualifier on address just to explicitly call out that this is not the address within the "virtual" app region flash.

Comment (bradjc) [reply capsules/extra/src/isolated_nonvolatile_storage_driver.rs]: Yeah that makes sense.

**Review by bradjc — APPROVED** [review]

File: capsules/extra/src/isolated_nonvolatile_storage_driver.rs (hunk 1 above)
Comment (tyler-potyondy) [reply capsules/extra/src/isolated_nonvolatile_storage_driver.rs]: I meant "absolute_address" as Pat suggested, not "physical" (due to the naming conflict). Just updated this naming and force pushed to overwrite the prior "global_address" change to now be "absolute_address".

**Review by bradjc — APPROVED** [review]

**Comment by bradjc** [comment]
@ppannuto Let's just merge this and worry about the variable names later.
