### PR TITLE
propagate additional process loading errors to main.rs

### LINKED ISSUE #1764: Lack of Error Signaling when insufficient app memory available
By default, libtock-c applications request 8kB of memory. On a board like Hail, `NUM_PROCS=20`, implying that 20 processes can be loaded. However `APP_MEMORY` on hail is set to 49 kB, so attempting to load more than 6 processes fails. Currently, this manifests as the first 6 processes loaded onto the board work as expected, and subsequently flashed apps are treated as if they do not exist. No error messages are printed and the only signal something is wrong is that some apps do not execute.

A developer encountering this problem can solve it by increasing `APP_MEMORY`, or by decreasing the amount of memory requested by apps in libtock-c -- but it can be confusing to debug.

Ideally, when a board is initialized, it should at least print a debug message if there is not enough memory to load all apps, or perhaps even panic. Alternatively, perhaps tockloader could print an error if an app is loaded that there is not enough memory for?

### PR DESCRIPTION
**Pull request by hudson-ayers**
### Pull Request Overview

This pull request modifies `process::create()` to return an error in 3 cases where previously it just returned an empty process slot -- if there is an error initializing the process, if there is an error allocating the MPU region for that process's flash, or if there is not enough memory to meet the amount requested by that process (or the minimum amount currently required by the kernel).

It adds one new `ProcessLoadError` variant: `ProcessLoadError::NotEnoughMemory`. Failures with allocating an MPU region or initializing a process are treated as `InternalError`'s. 

This PR fixes #1764 by making it so that failing to load a valid process is no longer a silent failure if the board chooses to handle the error.

### Testing Strategy

This pull request was tested by flashing 4 apps, each requesting 8kB of RAM, and observing they work as expected, then flashing 5 apps, each requesting 8kB of RAM, and observing that `load_processes()` fails, causing a debug message to be printed to the screen.

### TODO or Help Wanted

This modifies the existing behavior of `load_processes()` so that it returns as soon as any process fails to load, whereas currently it will continue trying to load processes even if one fails for one of the above 3 reasons. I think this behavior is better, especially given that boards can redefine `load_processes` if they want to, but am open to pushback on this.

### Documentation Updated

- [x] No updates are required.

### Formatting

- [x] Ran `make formatall`.

### CODE REVIEW

File: kernel/src/process.rs [hunk 1]
```diff
@@ -1595,13 +1604,13 @@ impl<C: 'static + Chip> Process<'a, C> {
...
                 debug!(
-                    "[!] flash=[{:#010X}:{:#010X}] process={:?} - couldn't allocate flash region",
+                    "[!] flash=[{:#010X}:{:#010X}] process={:?} - couldn't allocate MPU region for flash",
                     app_flash.as_ptr() as usize,
                     app_flash.as_ptr() as usize + app_flash.len(),
                     process_name
                 );
             }
-            return Ok((None, 0));
+            return Err(ProcessLoadError::InternalError);
```
Comment (bradjc) [inline kernel/src/process.rs:1613]: I'm not sure making this error `InternalError` is right. I think we want to save the internal error for only issues where the kernel is wrong. In this case, however, I think an app loaded with a length in flash that the MPU doesn't expect will cause an error, which is maybe arguably a kernel error, but the fix is to correct the app size, not patch the kernel.

Likely a new error would be better, one that indicates it could be the app or a bad MPU implementation.

**Comment by hudson-ayers** [comment]
Added a new error type for when the MPU does not support the flash length of an app

**Comment by ppannuto** [comment]
These are good changes, but since we're stalled on merging for a bit for 1.5 anyway, maybe this should keep bubbling up these errors and address https://github.com/tock/tock/issues/1225?

**Comment by hudson-ayers** [comment]
> These are good changes, but since we're stalled on merging for a bit for 1.5 anyway, maybe this should keep bubbling up these errors and address #1225?

I think that this does address #1225, at least for the process loading case? These errors are returned from `load_processes()` where they can be handled by `main.rs` (and are handled by `main.rs`, at least for Imix).
