### PR TITLE
cortex-m: Detect stack overflow

### LINKED ISSUE #1176: Hard Fault Handler Pushes to Stack
Currently, overflowing the kernel stack results in the hard fault handler being called, as the MPU ensures only valid memory regions can be accessed. However, the hard fault handler immediately pushes two registers onto the stack, resulting in yet another hard fault. This manifests in a complete lockup of the device, with no panic or debug info printed to the console, and no blinking LEDs to indicate a panic. 

Stepping through such a fault in gdb only shows that the board has halted within `hard_fault_handler()` in lib.rs, along with the message "clearing lockup after double fault". Further, backtrace does not work after this has occurred, as gdb detects that the stack has been corrupted. As a result, the only definitive clue that a stack overflow has occurred is that printing the registers reveals that the stack pointer is below 0x20000000. Stack overflows should lead to clear debug messages.

### PR DESCRIPTION
**Pull request by bradjc**
### Pull Request Overview

This pull request adds logic to the kernel hardfault handler to detect a stack overflow condition, and resets the stack before using it. With IPC on hail I'm able to trigger this case and verify I get the panic handler.

This also moves the userland state saving down below since I'm not sure why that code was run in both the kernel and userspace fault case.

Fixes #1176.

### Testing Strategy

Verifying that IPC on hail causes this panic handler to be displayed.

### TODO or Help Wanted

1. Someone to look over the assembly.

2. I can copy to m3 once we are happy with it. I'm not sure this will work on cortex-m0 due to differences in the SCB.

### Documentation Updated

- [x] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [x] Ran `make prepush`.

### CODE REVIEW

File: arch/cortex-m4/src/lib.rs [hunk 1]
```diff
@@ -444,52 +444,96 @@ pub unsafe extern "C" fn hard_fault_handler() {
...
+            // To make room for a panic!() handler stack, we just re-use the
+            // kernel's original stack. This should in theory leave the bottom
+            // of the stack where the problem occurred untouched should one want
+            // to further debug.
+            llvm_asm!(
+            "
+            mov sp, r0   /* Set the stack pointer to _estack */"
+            :
+            : "{r0}"((_estack as *const ()) as u32)
+            : );
```
Comment (ppannuto) [inline arch/cortex-m4/src/lib.rs:497]: This needs `volatile` (as there are no "externally visible" effects, aka no code depends on any register or variable values written to by this assembly)

File: arch/cortex-m4/src/lib.rs [hunk 2]
```diff
@@ -444,52 +444,96 @@ pub unsafe extern "C" fn hard_fault_handler() {
...
+
+        /* Set thread mode to privileged */
+        mov r0, #0
+        msr CONTROL, r0
+        /* CONTROL writes must be followed by ISB */
+        /* http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dai0321a/BIHFJCAC.html */
+        isb
+
+        movw LR, #0xFFF9
+        movt LR, #0xFFFF"
```
Comment (ppannuto) [inline arch/cortex-m4/src/lib.rs:536]: (comment for next line)

This doesn't seem to have been a problem before, but this assembly should mark its clobbers...

File: arch/cortex-m4/src/lib.rs (hunk 1 above)
Comment (bradjc) [inline arch/cortex-m4/src/lib.rs:497]:
```suggestion
            : "volatile" );
```

File: arch/cortex-m4/src/lib.rs [hunk 3]
```diff
@@ -444,52 +444,96 @@ pub unsafe extern "C" fn hard_fault_handler() {
...
+        tst   r2, #0x30        /* r2 = BFSR & 0b00110000; LSPERR & STKERR bits */
+        ite   ne               /* check if the result of that bitwise AND was not 0 */
+        movne r3, #1           /* BFSR & 0b00110000 != 0; r3 = 1 */
+        moveq r3, #0           /* BFSR & 0b00110000 == 0; r3 = 0 */"
+        : "={r3}"(stack_overflow)
+        :
+        : "r3"
+        : "volatile" );
+
+        if stack_overflow {
```
Comment (brghena) [inline arch/cortex-m4/src/lib.rs:482]: Shouldn't this run in both cases? Conceptually, an app error could cause a kernel stack overflow if the stack was already really close to full when the app had its error. I agree that that will likely never occur, but if it's possible and this logic can cleanly be moved above the `if kernel_stack {` then why not?

Comment (bradjc) [reply arch/cortex-m4/src/lib.rs:482]: In the app case we could. I guess the idea is who cares about the kernel stack if an app faulted?

In the kernel case we probably can? We do want to read values the hw pushed on the kernel stack but assuming calling `kernel_hardfault` doesn't overwrite those it would be fine. But I think the bigger issue is someone would probably want to be able to debug the kernel stack if their kernel hardfaults.

Comment (brghena) [reply arch/cortex-m4/src/lib.rs:482]: I guess what I'm saying is that I think an application error could still cause a double-hardfault. For example, assume an application error occurs, so the `hardfault_handler` is called, but before that, various registers are placed on the kernel stack. If the kernel stack was nearly full at that time, it could now overflow which would be detected by your stack_overflow check, but we came from an app instead of the kernel.

We don't actually use the stack pointer in the from-userland portion of the `hardfault_handler` though, so another hardfault would only occur when returning from this handler into the middle of the user swap code. So maybe that would just be end up triggering a from-kernel hardfault which you would catch? I'm not really sure of the specifics there.

A defense against this would be to just check the kernel stack for overflows no matter where we come from. Because if there was an overflow, I've got problems I want to know about, even if it was an app that surfaced it.

Comment (bradjc) [reply arch/cortex-m4/src/lib.rs:482]: The HW pushes values on to the kernel stack if an app faults? Where do we reset the kernel stack when that happens? Do we actually need to? Arg why is none of this code commented. I feel like I missed the class where all of this cortexm hardware magic was explained.

Comment (bradjc) [reply arch/cortex-m4/src/lib.rs:482]: Is it possible for the kernel stack to be nearly full when an application is executed? Since we only call switch_to in one place, can a long stack actually occur? Or, how could one test this to see what happens?

Comment (brghena) [reply arch/cortex-m4/src/lib.rs:482]: The hardware needs to push all caller-saved registers so that the interrupt handler doesn't overwrite them. (https://interrupt.memfault.com/blog/arm-cortex-m-exceptions-and-nvic#exception-entry--exit) It automatically adjusts the stack pointer too. However, the ARM documentation suggests that the hardware uses the _current_ stack to place the caller-saved registers on. (https://stackoverflow.com/questions/45461739/which-stack-is-used-when-entering-interrupt-handler-from-user-program-for-cortex) So an exception from userland cannot cause a kernel stack overflow (although it could cause an application stack overflow).

I also agree that in proper execution, the kernel stack should not be nearly full when an application is executed, so this shouldn't come up anyways.

**Comment by bradjc** [comment]
@tock/core-wg

File: arch/cortex-m4/src/lib.rs (hunk 2 above)
Comment (ppannuto) [reply arch/cortex-m4/src/lib.rs:536]: Moved to #2037.
