### PR TITLE
esp32-c3: fix reading timer, make makefile more generic

### LINKED ISSUE #4634: ESP32-C3-DevKitM-1 updates and issues
Hello, I am new to tock and I am trying to boot tock using the instructions here: https://github.com/tock/tock/tree/master/boards/esp32-c3-devkitM-1

The kernel panics at kernel/src/utilities/static_init.rs:70:9: Error! Single static_buf!() called twice.

Is this a known issue? What are the best ways to debug the kernel? Is there a way to print stack trace, until I setup jtag?

### PR DESCRIPTION
**Pull request by bradjc**
### Pull Request Overview

This fixes #4634 where when Tock runs on the ESP32-C3 a soft reset occurs, causing the boot to run again with memory not cleared, causing static init failures.

After much hacking I've come up with two fixes for the ESP32-C3 board:

1. Initially I thought the issue was with the timer interrupt. When debugging that I noticed that the first call to `alarm.now()` would return the old count value. Adding a second call the sync register fixes that and avoids the alarm stack getting wrong values for now and triggering an unnecessary interrupt.
~~2. After it wasn't the timer I realized the issue was with the UART interrupt. I tried many many things, clearing interrupts, using different UART interrupts, etc. The only thing that fixed it was using a different CPU interrupt number. I just chose 23 fairly arbitrarily. I can't explain why this fixes it, but it does.~~

Also to use the board I need to remove the defined port in the `make flash` command, so I removed that too.

### Testing Strategy

Running the tock process console on the board.

### TODO or Help Wanted

n/a

### Documentation Updated

- [x] Updated the relevant files in `/docs`, or no updates are required.

### Formatting

- [x] Ran `make prepush`.

### CODE REVIEW

File: chips/esp32/src/timg.rs [hunk 1]
```diff
@@ -194,9 +194,14 @@ impl<F: time::Frequency, const C3: bool> time::Time for TimG<'_, F, C3> {
...
-        // a write (of any value) to T0UPDATE stores the
-        // current counter value to T0LO and T0HI
+        // According to the datasheet, a write (of any value) to T0UPDATE stores
+        // the current counter value to T0LO and T0HI. However, in my (bradjc)
+        // testing the first read of t0lo and t0hi after a single write to
+        // t0update returned the old counter value. Writing two values to
+        // t0update seems to fix this.
         self.registers.t0update.set(0xABC);
+        self.registers.t0update.set(0x8000_0000);
+
```
Comment (ppannuto) [inline chips/esp32/src/timg.rs]: Image

I believe this needs to loop/poll until `t0update.get() == 0`

File: chips/esp32-c3/src/interrupts.rs [hunk 2]
```diff
@@ -28,9 +28,12 @@ pub const IRQ_GPIO_NMI: u32 = 17;
...
 pub const IRQ_SPI2: u32 = 19;
 pub const IRQ_I2S1: u32 = 20;
-pub const IRQ_UART0: u32 = 21;
+/// This deviates from the index used in the datasheet, but for some reason
+/// using 21 causes the chip to soft reset. Using 23 was arbitrarily chosen.
+pub const IRQ_UART0: u32 = 23;
 pub const IRQ_UART1: u32 = 22;
-pub const IRQ_LEDC: u32 = 23;
+/// Swapped with IRQ_UART0.
+pub const IRQ_LEDC: u32 = 21;
```
Comment (ppannuto) [inline chips/esp32-c3/src/interrupts.rs]: This one is less immediately obvious, but two (related) questions — did you try values other than 23? Are there any pattern to the values that work?

<details>
  <summary>Wrong rabbit hole; saved for posterity / vector table alignment is correct</summary>

I'm probing at the alignment of `mtvec`, which the datasheet says needs to be 256-byte aligned. And we do make sure that the vector table (`_start_trap_vectored`) is by placing first in the aligned block in the linker script:

        KEEP(*(.riscv.start));
        /* For RISC-V we need the `_start_trap` function to be 256 byte aligned,
         * and that function is at the start of the .riscv.trap section. If that
         * function does not exist (as for non-RISC-V platforms) then we do not
         * need any unusual alignment.
         * The alignment is implementation specific, so we currently use 256 to
         * work with the lowRISC CPUs.
         */
        . = DEFINED(_start_trap) ? ALIGN(256) : ALIGN(1);
        KEEP(*(.riscv.trap_vectored));
        KEEP(*(.riscv.trap));

But the actual value that we write to `mtvec` isn't the `_start_trap_vectored` symbol, rather it is the `_start_trap` symbol:

    #[cfg(any(doc, all(target_arch = "riscv32", target_os = "none")))]
    #[link_section = ".riscv.trap"]
    #[unsafe(naked)]
    pub extern "C" fn _start_trap() {
        use core::arch::naked_asm;
        naked_asm!(...

~which will definitionally _not_ 256-byte aligned (since `_start_trap` comes right after `_start_trap_vectored`, and `_start_trip` is 32 bytes~ nope, 32 words * 8 bytes = 256 bytes, okay, so it _shouldn't_ be an alignment thing; at least not that alignment
</details>

Comment (bradjc) [reply chips/esp32-c3/src/interrupts.rs]: Haha you were right. The issue is the alignment.

File: chips/esp32/src/timg.rs (hunk 1 above)
Comment (bradjc) [reply chips/esp32/src/timg.rs]: Fixed.

**Comment by bradjc** [comment]
Ok this PR just fixes the timer and the makefile. Fix to get UART to work is in #4644.

File: chips/esp32-c3/src/interrupts.rs (hunk 2 above)
Comment (bradjc) [reply chips/esp32-c3/src/interrupts.rs]: I too had the same thought you did, and I too looked at that and thought "oh we definitely have that symbol, so the alignment is fine". Oops.
